---
development:
  dialect: "sqlite3"
  database: /home/riton/Sources/toutdoux_toutdoux_development.sqlite

test:
  dialect: "sqlite3"
  database: /home/riton/Sources/toutdoux_toutdoux_test.sqlite

production:
  dialect: "sqlite3"
  database: /home/riton/Sources/toutdoux_toutdoux_production.sqlite
