---
development:
  dialect: "sqlite3"
  database: /home/riton/Sources/toutdoux/toutdoux_development.sqlite

test:
  dialect: "sqlite3"
  database: /home/riton/Sources/toutdoux/toutdoux_test.sqlite

production:
  dialect: "sqlite3"
  database: /home/riton/Sources/toutdoux/toutdoux_production.sqlite
